FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Этап запуска
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

# Порт для Nginx
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
