FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# Копируем все файлы проекта
COPY . .

# Указываем порт, на котором будет работать сервер
EXPOSE 3000

# Запуск приложения
CMD ["npm", "start"]
